cad:
- CAD/Panel_right.step
- CAD/Panel_left.step
description: Panels with intergrated hinge
images:
- Images/1.jpg
- Images/4.jpg
- Images/5.jpg
- Images/2.jpg
- Images/3.jpg
mod_version: 1
printer_compatibility:
- V0.2
title: Side Panels
